TicTacToe Project
NFSS10/Programar-com-o-Daniel pull request #4
Opened 2020-06-10 12:33 UTC by dfobastos

Primeiros dois passos completos:

- Introduzir o nome do jogador 1 e jogador 2;
- Lançamento de uma moeda para ver quem é o primeiro a jogar

2020-06-10 12:35 UTC, NFSS10 commented
Noice

2020-06-10 14:48 UTC, NFSS10 commented on TicTacToe.py
> +lancamento2 = random.randrange(0,1)
Qual foi a tua ideia aqui?
Fazes um primeiro lançamento para ver quem fica com cara e com a coroa e depois fazes outro lançamento para ver o que sai e definir quem é o primeiro a jogar?

2020-06-10 15:41 UTC, dfobastos commented on TicTacToe.py
> +lancamento2 = random.randrange(0,1)
O primeiro jogador tem a possibilidade de escolher se quer cara ou coroa, se o mesmo escolher cara automaticamente a "coroa" irá ser atribuída ao segundo jogador, e assim vice-versa.

O segundo lançamento serviu para a moeda ser lançada e ver quem vai ser o jogador que irá iniciar.

2020-06-29 19:59 UTC, NFSS10 requested changes

2020-06-29 19:59 UTC, NFSS10 commented on DesenharTabuleiro.py
> +
@dfobastos Então, sempre conseguis-te resolver estas tarefas?

2022-02-22 09:21 UTC, merged